fields:
    primary: 'id_product_attribute, id_image'
    columns:
        id_product_attribute:
          relation: ProductAttribute
          generate_all: true
        id_image:
          relation: Image